name: azure-deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:  
  ARM_USE_OIDC: true  
  ARM_USE_AZUREAD: true  
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}  
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}  
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  plan-terraform:
    runs-on: ubuntu-latest
    outputs:
      plancode: ${{ steps.tfplan.outputs.exitcode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        id: tfplan
        run: |
          set +e
          terraform plan -detailed-exitcode -out=tfplan
          code=$?
          echo "exitcode=$code" >> $GITHUB_OUTPUT
          terraform show -no-color tfplan > plan.txt
          if [ $code -eq 1 ]; then exit 1; fi
          exit 0
      - name: upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            tfplan
            plan.txt
          retention-days: 1
  apply-terraform:
    needs: plan-terraform
    runs-on: ubuntu-latest
    if: needs.plan-terraform.outputs.plancode == '2'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: terraform init
        run: terraform init
      - name: terraform apply
        run: terraform apply -auto-approve tfplan